version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ci_app
    volumes:
      - ./:/var/www/html
      - session_data:/var/www/html/application/sessions
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ci_network
    
      


  db:
    image: mysql:5.7
    container_name: ci_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
    ports:
      - "3306:3306"
    networks:
      - ci_network

  webserver:
    image: nginx:alpine
    container_name: ci_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ci_network

volumes:
  db_data:
  session_data:

networks:
  ci_network:
    driver: bridge